# Generated by Django 4.2 on 2025-01-09 15:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controlMantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='fecha_proximo_mantenimiento',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='kilometraje',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='kilometraje_proximo_mantenimiento',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tipomantenimiento',
            name='kilometraje_promedio',
            field=models.IntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_mantenimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='HistorialKilometraje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('Salida', 'Salida'), ('Entrada', 'Entrada')], default='Salida', max_length=15)),
                ('kilometraje', models.IntegerField()),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controlMantenimiento.vehiculo')),
            ],
        ),
    ]
