# Generated by Django 4.2 on 2025-01-09 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controlMantenimiento', '0002_remove_mantenimiento_fecha_proximo_mantenimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='kilometraje_proximo_mantenimiento',
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='fecha de emision'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_expiracion',
            field=models.DateField(verbose_name='fecha de expiracion'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('Tarjeta de Circulacion', 'Tarjeta de Circulacion'), ('Licencia de Conducir', 'Licencia de Conducir'), ('Soat', 'Soat'), ('Tarjeta de Propiedad', 'Tarjeta de Propiedad'), ('Revision Tecnica', 'Revision Tecnica'), ('Permiso de Recojo de Reciduos', 'Permiso de Recojo de Reciduos'), ('Certificado de Aptitud Psicofisica', 'Certificado de Aptitud Psicofisica'), ('Capacitacion', 'Capacitacion'), ('Otro', 'Otro')], max_length=50, verbose_name='tipo de documento'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='numero_placa',
            field=models.CharField(max_length=20, unique=True, verbose_name='numero de placa'),
        ),
    ]
