# Generated by Django 4.2 on 2025-01-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlMantenimiento', '0003_remove_mantenimiento_kilometraje_proximo_mantenimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='kilometraje_proximo_mantenimiento',
            field=models.IntegerField(null=True),
        ),
    ]
