# Generated by Django 4.2 on 2025-01-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlMantenimiento', '0005_alter_mantenimiento_kilometraje_proximo_mantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='kilometraje_proximo_mantenimiento',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
