# Generated by Django 4.2 on 2025-01-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlMantenimiento', '0006_alter_mantenimiento_kilometraje_proximo_mantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Atendido', 'Atendidos')], default='Pendiente', max_length=15),
        ),
    ]
