# Generated by Django 4.2 on 2025-01-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlMantenimiento', '0007_mantenimiento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Atendido', 'Atendido')], default='Pendiente', max_length=15),
        ),
    ]
