# Generated by Django 4.2 on 2025-01-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlMantenimiento', '0008_alter_mantenimiento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Tramitado', 'Tramitado')], default='Pendiente', max_length=15),
        ),
    ]
