# Generated by Django 4.2 on 2025-01-15 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controlMantenimiento', '0009_documento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='fecha_expiracion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='fecha de expiracion'),
        ),
    ]
