# Generated by Django 5.0.7 on 2024-08-12 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControlVehiculos', '0004_alter_document_car_alter_expense_route_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='descipcion',
            new_name='descripcion',
        ),
    ]
