# Generated by Django 5.0.7 on 2024-08-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlVehiculos', '0005_rename_descipcion_expense_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='modelo',
            field=models.CharField(max_length=20),
        ),
    ]
